manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: spreng
      url-base: https://github.com/spreng

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: pmw3610-zmk-driver
      remote: spreng
      revision: main

  self:
    path: config
